### ISSUE TITLE
屏蔽 *

### ISSUE THREAD

**Issue by zhy7557455** [ice1000/A8Translate#13]
看源码的时候注释里的*就翻译不出来，希望改进一下

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/52924224-cbdcc700-32f9-11e9-922f-c9c6e8ae20ce.png)

**Comment by zhy7557455** [comment]
![jru2e xxf eo5 za 26su](https://user-images.githubusercontent.com/42531411/52924309-32e49500-3367-11e9-8ed0-eba7023550d7.png)

**Comment by ice1000** [comment]
……我刚更新啊，新的插件包正在审核……
