### ISSUE TITLE
大佬，能否默认设置为鼠标悬浮获取整行或者区块并翻译？

### ISSUE THREAD

**Issue by misitebao** [ice1000/A8Translate#15]
之前使用vscode，它有一个插件[](https://github.com/intellism/vscode-comment-translate) 是鼠标悬浮注释位置，会自动获取当前鼠标悬浮位置的注释内容，不管是单行注释还是多行注释然后翻译显示出来，显示格式和注释格式一样，该换行的换行。

具体的大佬可以安装参考下。下图是我鼠标悬浮然后自动翻译的 并没有用鼠标选中文字。
![image](https://user-images.githubusercontent.com/28185258/86561507-60010a00-bf93-11ea-9cf9-cc407a8db021.png)

**Comment by ice1000** [comment]
这个得每个编程语言写单独的支持，挺难办的。我得想想办法。

**Comment by misitebao** [comment]
可以暂时只识别 // 开头的呀Go注释基本都是双斜杠注释

**Comment by ice1000** [comment]
IntelliJ 能拿文件的 AST，那么自己去解析文件就应该是一种不好的实践

**Comment by misitebao** [comment]
好吧 了解了

**Comment by rxliuli** [comment]
有任何进展么？

**Comment by ice1000** [comment]
> 有任何进展么？

我实际上的感觉是没有什么必要…………………………如果悬浮就翻译的话，很容易无意中触发大量的翻译从而导致 API 受限（见 #16），而且选中注释也很简单，光标放进注释后 C-w（可能需要多按几次）就可以选中整段注释

**Comment by rxliuli** [comment]
> > 有任何进展么？
> 
> 我实际上的感觉是没有什么必要………………………… 如果悬浮就翻译的话，很容易无意中触发大量的翻译从而导致 API 受限（见 #3），而且选中注释也很简单，光标放进注释后 C-w（可能需要多按几次）就可以选中整段注释

吾辈的误解，Google 翻译就没限制了

**Comment by ice1000** [comment]
> > > 有任何进展么？
> > 
> > 
> > 我实际上的感觉是没有什么必要………………………… 如果悬浮就翻译的话，很容易无意中触发大量的翻译从而导致 API 受限（见 #3），而且选中注释也很简单，光标放进注释后 C-w（可能需要多按几次）就可以选中整段注释
> 
> 吾辈的误解，Google 翻译就没限制了

https://github.com/ice1000/A8Translate/issues/19#issuecomment-765487374
