### ISSUE TITLE
中文部分乱码.

### ISSUE THREAD

**Issue by Houtx** [ice1000/A8Translate#17]
环境:
    插件版本1.8.
    idea2020.1.

截图:
![image](https://user-images.githubusercontent.com/17922172/88869538-a883ae80-d245-11ea-8a81-4d8253622507.png)
![image](https://user-images.githubusercontent.com/17922172/88869561-b5a09d80-d245-11ea-9b57-4817ce0231a0.png)
![image](https://user-images.githubusercontent.com/17922172/88869587-c2bd8c80-d245-11ea-8fce-25bea730cc8a.png)

有的单词翻译是乱码, 有的不是乱码, 就很奇怪. 麻烦看一下

**Comment by ice1000** [comment]
我不懂啊 
![image](https://user-images.githubusercontent.com/16398479/88928104-fbdc1800-d2aa-11ea-8e63-e4b7120e6ffd.png)

**Comment by Houtx** [comment]
> 我不懂啊
> ![image](https://user-images.githubusercontent.com/16398479/88928104-fbdc1800-d2aa-11ea-8e63-e4b7120e6ffd.png)

就很奇怪...

**Comment by ice1000** [comment]
> 就很奇怪...

是啊，很奇怪
![image](https://user-images.githubusercontent.com/16398479/89658526-3f650080-d901-11ea-92ff-91f7675cbf4d.png)
