### ISSUE TITLE
中文乱码问题

### ISSUE THREAD

**Issue by heicks** [ice1000/A8Translate#2]
慢悠悠的显示出来(非固态,卡卡的).....   另外这个不能翻译句子吗?

单个的词儿没问题,可以正常翻译一切ok,
 感觉这调用的是api吧, 句子应该也能翻译的了,中文乱码- -
![image](https://user-images.githubusercontent.com/12287943/34351180-e4b9b64a-ea55-11e7-8ca6-ad58af6bf252.png)
![image](https://user-images.githubusercontent.com/12287943/34351200-02a67490-ea56-11e7-8243-b75892206994.png)

**Comment by ice1000** [comment]
是调用的API，有道翻译的。。。

然后这个东西显示出来慢是因为网速慢。。淡入淡出也是IntelliJ IDEA自己的效果，不是我加的。。

**Comment by ice1000** [comment]
麻烦您能提供一下 `[用户目录]/a8temp.properties`文件吗？

**Comment by ice1000** [comment]
这样我可以调试一下这个乱码问题

**Comment by heicks** [comment]
那能不能去掉呀0.0  win7自带的淡入淡出都被我勾没了

选择右侧边上的,慢慢往左选就这样错位了, 或者反过来也可以
![image](https://user-images.githubusercontent.com/12287943/34368651-6747ba9a-eaf0-11e7-83f4-c19eacc9f80f.png)

对了, 那个color: #497549框鼠标放上去能不自动隐藏吗?移开随便了, 鼠标放上去想记一下, 结果gg了0.0

![image](https://user-images.githubusercontent.com/12287943/34368733-23aeaf9a-eaf1-11e7-952b-da5c2096ecf7.png)

**Comment by heicks** [comment]
![image](https://user-images.githubusercontent.com/12287943/34368815-d293b2c6-eaf1-11e7-9133-b999b41db59e.png)

文件上传不上去, 复制内容粘贴了....

` # Created by a8translate
 # Wed Dec 27 10: 31: 23 GMT + 08: 00 2017
width = {
	"translation" \ : ["宽度"],
	"basic" \ : {
		"us-phonetic" \ : "w?dθ",
		"phonetic" \ : "w?tθ; w?dθ",
		"uk-phonetic" \ : "w?tθ; w?dθ",
		"explains" \ : ["n. 宽度；广度"]
	},
	"query" \ : "width",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["宽度", "仓库", "宽阔"],
			"key" \ : "Width"
		}, {
			"value" \ : ["钮牌阔", "门襟宽", "钮牌宽"],
			"key" \ : "FLY WIDTH"
		}, {
			"value" \ : ["介英宽", "袖头宽", "袖口宽"],
			"key" \ : "CUFF WIDTH"
		}
	]
}
center = {
	"translation" \ : ["中心"],
	"basic" \ : {
		"us-phonetic" \ : "'s?nt?",
		"phonetic" \ : "?sent?(r)",
		"uk-phonetic" \ : "?sent?(r)",
		"explains" \ : ["n. 中心，中央；中锋；中心点", "adj. 中央的，位在正中的", "vt. 集中，使聚集在一点；定中心", "vi. 居中，被置于中心", "n. (Center)人名；(英)森特"]
	},
	"query" \ : "center",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["中锋", "中心", "中锋"],
			"key" \ : "Center"
		}, {
			"value" \ : ["资料中心", "数据中心", "数据中心"],
			"key" \ : "data center"
		}, {
			"value" \ : ["中心线", "中线", "舞台中心线"],
			"key" \ : "Center line"
		}
	]
}
电弧故障断路器 = {
	"query" \ : "???????????·?÷",
	"errorCode" \ : 30
}
carousel = {
	"translation" \ : ["旋转木马"],
	"basic" \ : {
		"us-phonetic" \ : "'k?r?'s?l",
		"phonetic" \ : ",k?r?'sel; -'zel",
		"uk-phonetic" \ : ",k?r?'sel; -'zel",
		"explains" \ : ["n. 旋转木马；行李传送带；轮播"]
	},
	"query" \ : "carousel",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["旋转木马", "圆盘传送带", "天上人间"],
			"key" \ : "Carousel"
		}, {
			"value" \ : ["喧闹的酒会进行曲"],
			"key" \ : "CAROUSEL MARCH"
		}, {
			"value" \ : ["酒会", "男人"],
			"key" \ : "Carousel Man"
		}
	]
}
shortcut = {
	"translation" \ : ["快捷方式"],
	"basic" \ : {
		"us-phonetic" \ : "'??rt,k?t",
		"phonetic" \ : "'???tk?t",
		"uk-phonetic" \ : "'???tk?t",
		"explains" \ : ["n. 捷径；被切短的东西"]
	},
	"query" \ : "shortcut",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["快捷键", "快捷方式", "快捷"],
			"key" \ : "shortcut"
		}, {
			"value" \ : ["快捷键", "快速键", "快捷健"],
			"key" \ : "Shortcut Key"
		}, {
			"value" \ : ["快捷键", "热键", "运转程序或执行命令的一组键"],
			"key" \ : "Shortcut Keys"
		}
	]
}
rounded = {
	"translation" \ : ["圆形的"],
	"basic" \ : {
		"us-phonetic" \ : "'ra?nd?d",
		"phonetic" \ : "'ra?nd?d",
		"uk-phonetic" \ : "'ra?nd?d",
		"explains" \ : ["adj. 圆形的；全面的；丰满的"]
	},
	"query" \ : "rounded",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["浑圆", "全面的", "半球型"],
			"key" \ : "Rounded"
		}, {
			"value" \ : ["修圆的舷边", "弧形舷缘", "圆弧舷缘"],
			"key" \ : "rounded gunwale"
		}, {
			"value" \ : ["滚圆颗粒", "圆形砂", "圆粒"],
			"key" \ : "rounded grain"
		}
	]
}
bookmark = {
	"translation" \ : ["书签"],
	"basic" \ : {
		"us-phonetic" \ : "'b?kmɑrk",
		"phonetic" \ : "'b?kmɑ?k",
		"uk-phonetic" \ : "'b?kmɑ?k",
		"explains" \ : ["n. 书签（等于bookmarker）；标记"]
	},
	"query" \ : "bookmark",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["书签", "书签 (浏览器)", "书签文件"],
			"key" \ : "Bookmark"
		}, {
			"value" \ : ["书签查找", "书签查询"],
			"key" \ : "Bookmark Lookup"
		}, {
			"value" \ : ["新建书签"],
			"key" \ : "New bookmark"
		}
	]
}
证书 = {
	"translation" \ : ["?¤?é"],
	"query" \ : "?¤?é",
	"errorCode" \ : 0
}
dlq2 = {
	"translation" \ : ["dlq2"],
	"query" \ : "dlq2",
	"errorCode" \ : 0
}
造成虚接 = {
	"translation" \ : ["?ì???é??"],
	"query" \ : "?ì???é??",
	"errorCode" \ : 0
}
新闻 = {
	"translation" \ : ["????"],
	"query" \ : "????",
	"errorCode" \ : 0
}
50 = {
	"translation" \ : ["50"],
	"basic" \ : {
		"explains" \ : ["fifty"]
	},
	"query" \ : "50",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["50年", "大", "得到"],
			"key" \ : "50"
		}, {
			"value" \ : ["巾部"],
			"key" \ : "Radical 50"
		}, {
			"value" \ : ["M50 (疏散星团)"],
			"key" \ : "Messier 50"
		}
	]
}
navbar - collapse = {
	"translation" \ : ["navbar-collapse"],
	"query" \ : "navbar-collapse",
	"errorCode" \ : 0
}
产品 = {
	"query" \ : "?ú?·",
	"errorCode" \ : 30
}
cHARSET = {
	"translation" \ : ["字符集"],
	"basic" \ : {
		"explains" \ : ["n. 字符集；字元集"]
	},
	"query" \ : "charset",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["字符集", "字元集", "字符编码"],
			"key" \ : "charset"
		}, {
			"value" \ : ["文本信息所使用的字符集"],
			"key" \ : "text  charset"
		}, {
			"value" \ : ["输出字符集编码"],
			"key" \ : "Output Charset"
		}
	]
}
blank = {
	"translation" \ : ["空白"],
	"basic" \ : {
		"us-phonetic" \ : "bl??k",
		"phonetic" \ : "bl??k",
		"uk-phonetic" \ : "bl??k",
		"explains" \ : ["n. 空白；空虚；空白表格", "adj. 空白的；空虚的；单调的", "vt. 使\\u2026无效；使\\u2026模糊；封锁", "vi. 消失；成为空白", "n. (Blank)人名；(法)布朗克；(英、德、西、俄、罗、捷、瑞典、芬)布兰克"]
	},
	"query" \ : "blank",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["空白", "空包弹", "毛坯"],
			"key" \ : "Blank"
		}, {
			"value" \ : ["无韵诗", "无韵诗", "素体诗"],
			"key" \ : "Blank verse"
		}, {
			"value" \ : ["史蒂夫·布兰克", "史蒂夫·布兰克", "布兰科"],
			"key" \ : "Steve Blank"
		}
	]
}
fixed = {
	"translation" \ : ["固定"],
	"basic" \ : {
		"us-phonetic" \ : "f?kst",
		"phonetic" \ : "f?kst",
		"uk-phonetic" \ : "f?kst",
		"explains" \ : ["adj. 确定的；固执的；<美口>处境...的；准备好的", "v. 修理（过去式）"]
	},
	"query" \ : "fixed",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["固定", "定点", "不固定"],
			"key" \ : "Fixed"
		}, {
			"value" \ : ["固定成本", "固定成本", "不变成本"],
			"key" \ : "fixed cost"
		}, {
			"value" \ : ["固定资产", "固定资产管理", "在企业日常经营中长期或相对持久使用的有形资产"],
			"key" \ : "fixed assets"
		}
	]
}
_blank = {
	"translation" \ : ["平等自愿"],
	"basic" \ : {
		"us-phonetic" \ : "bl??k",
		"phonetic" \ : "bl??k",
		"uk-phonetic" \ : "bl??k",
		"explains" \ : ["adj. 空白的；空虚的；单调的", "n. 空白；空虚；空白表格", "vt. 使\\u2026无效；使\\u2026模糊；封锁", "vi. 消失；成为空白", "n. (Blank)人名；(法)布朗克；(英、德、西、俄、罗、捷、瑞典、芬)布兰克"]
	},
	"query" \ : "blank",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["压边力"],
			"key" \ : "blank_holder force"
		}, {
			"value" \ : ["浮动压边圈"],
			"key" \ : "floating blank_holding ring"
		}, {
			"value" \ : ["刚性压边圈"],
			"key" \ : "rigid blank_holding ring"
		}
	]
}
tHDH = {
	"translation" \ : ["THDH"],
	"query" \ : "THDH",
	"errorCode" \ : 0
}
responsive \ center = {
	"translation" \ : ["响应中心"],
	"query" \ : "responsive center",
	"errorCode" \ : 0
}
增加了过温保护 = {
	"translation" \ : ["??????????¤\\u201D±?"],
	"query" \ : "??????????±??¤",
	"errorCode" \ : 0
}
center - block = {
	"translation" \ : ["center-block"],
	"basic" \ : {
		"explains" \ : ["中心楔块"]
	},
	"query" \ : "center block",
	"errorCode" \ : 0
}
navigation = {
	"translation" \ : ["导航"],
	"basic" \ : {
		"us-phonetic" \ : "'n?v?'ge??n",
		"phonetic" \ : "n?v?'ge??(?)n",
		"uk-phonetic" \ : "n?v?'ge??(?)n",
		"explains" \ : ["n. 航行；航海"]
	},
	"query" \ : "navigation",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["导航", "航行", "航海"],
			"key" \ : "Navigation"
		}, {
			"value" \ : ["浏览"],
			"key" \ : "Navigation"
		}, {
			"value" \ : ["无线电导航", "无线电航行法", "无线电导航<火>"],
			"key" \ : "radio navigation"
		}
	]
}
tHDH系列隔离开关 = {
	"translation" \ : ["THDH??????????在?"],
	"query" \ : "THDH????????????",
	"errorCode" \ : 0
}
端子温度监控微型断路器在原有断路器功能基础上 = {
	"query" \ : "??×??????à?????????·?÷?????????·?÷?????ù????",
	"errorCode" \ : 30
}
circle = {
	"translation" \ : ["圆"],
	"basic" \ : {
		"us-phonetic" \ : "'s?kl",
		"phonetic" \ : "'s??k(?)l",
		"uk-phonetic" \ : "'s??k(?)l",
		"explains" \ : ["n. 循环，周期；圆；圈子；圆形物", "vt. 画圆圈；环绕\\u2026移动", "vi. 盘旋，旋转；环行"]
	},
	"query" \ : "circle",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["圈子", "圆", "圆形"],
			"key" \ : "Circle"
		}, {
			"value" \ : ["旁切圆", "内切圆", "内接圆"],
			"key" \ : "Inscribed circle"
		}, {
			"value" \ : ["辣妹掌门人 (日本电视剧)", "辣妹掌门人", "藤木直人"],
			"key" \ : "Gal Circle"
		}
	]
}
navbar = {
	"translation" \ : ["导航条"],
	"query" \ : "NavBar",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["导航条", "导航栏", "导航"],
			"key" \ : "NavBar"
		}, {
			"value" \ : ["导航按钮的改进"],
			"key" \ : "Bevelled Navbar Buttons"
		}, {
			"value" \ : ["侧栏"],
			"key" \ : "navbar&quot"
		}
	]
}
collapse = {
	"translation" \ : ["崩溃"],
	"basic" \ : {
		"us-phonetic" \ : "k?'l?ps",
		"phonetic" \ : "k?'l?ps",
		"uk-phonetic" \ : "k?'l?ps",
		"explains" \ : ["n. 倒塌；失败；衰竭", "vt. 使倒塌，使崩溃；使萎陷；折叠", "vi. 倒塌；瓦解；暴跌"]
	},
	"query" \ : "collapse",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["崩溃", "倒塌", "坍塌"],
			"key" \ : "Collapse"
		}, {
			"value" \ : ["全部折叠", "收缩所有", "全部坍塌"],
			"key" \ : "Collapse All"
		}, {
			"value" \ : ["合并继承层次", "折叠继承体系", "塌陷层级"],
			"key" \ : "Collapse Hierarchy"
		}
	]
}
inner = {
	"translation" \ : ["内心的"],
	"basic" \ : {
		"us-phonetic" \ : "'?n?",
		"phonetic" \ : "?n?",
		"uk-phonetic" \ : "?n?",
		"explains" \ : ["n. 内部", "adj. 内部的；内心的；精神的"]
	},
	"query" \ : "inner",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["内部的", "内在的", "内"],
			"key" \ : "inner"
		}, {
			"value" \ : ["内伦敦", "伦敦地区", "伦敦"],
			"key" \ : "Inner London"
		}, {
			"value" \ : ["内部类", "内隐类别", "内部类别"],
			"key" \ : "Inner Class"
		}
	]
}
toggle = {
	"translation" \ : ["切换"],
	"basic" \ : {
		"us-phonetic" \ : "'tɑɡl",
		"phonetic" \ : "'t?g(?)l",
		"uk-phonetic" \ : "'t?g(?)l",
		"explains" \ : ["n. 开关，触发器；拴扣；[船] 套索钉", "vt. 拴牢，系紧"]
	},
	"query" \ : "toggle",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["开关", "切换", "拨动"],
			"key" \ : "toggle"
		}, {
			"value" \ : ["肘形机构", "肘节机构", "拨动机构"],
			"key" \ : "toggle mechanism"
		}, {
			"value" \ : ["肘杆式压力机", "肘杆压机", "曲柄杠杆冲床"],
			"key" \ : "toggle press"
		}
	]
}
company \ Profile = {
	"translation" \ : ["公司简介"],
	"basic" \ : {
		"explains" \ : ["公司简介；公司概况；企业介绍"]
	},
	"query" \ : "company profile",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["公司简介", "公司介绍", "公司概况"],
			"key" \ : "Company Profile"
		}, {
			"value" \ : ["公司简介"],
			"key" \ : "Company   profile"
		}, {
			"value" \ : ["公司简介"],
			"key" \ : "company-profile"
		}
	]
}
安装方便等特点 = {
	"query" \ : "°?×°·?±???????",
	"errorCode" \ : 30
}
title = {
	"translation" \ : ["标题"],
	"basic" \ : {
		"us-phonetic" \ : "'ta?tl",
		"phonetic" \ : "'ta?t(?)l",
		"uk-phonetic" \ : "'ta?t(?)l",
		"explains" \ : ["n. 冠军；标题；头衔；权利；字幕", "adj. 冠军的；标题的；头衔的", "vt. 加标题于；赋予头衔；把\\u2026称为"]
	},
	"query" \ : "title",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["标题", "题目", "头衔"],
			"key" \ : "Title"
		}, {
			"value" \ : ["标题标签", "页面标题", "页面题目"],
			"key" \ : "title tag"
		}, {
			"value" \ : ["页面标题", "网页标题", "英文叫"],
			"key" \ : "Page title"
		}
	]
}
能引燃周围的易燃易爆品 = {
	"query" \ : "?????????§???×???×±??·",
	"errorCode" \ : 30
}
cont = {
	"translation" \ : ["续"],
	"basic" \ : {
		"us-phonetic" \ : "k?nt",
		"phonetic" \ : "k?nt",
		"uk-phonetic" \ : "k?nt",
		"explains" \ : ["abbr. 内容（contents）；连续的（continued）", "n. (Cont)人名；(西)孔特"]
	},
	"query" \ : "cont",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["对比度", "副对比度", "合同"],
			"key" \ : "CONT"
		}, {
			"value" \ : ["曲面连续"],
			"key" \ : "Surf Cont"
		}, {
			"value" \ : ["基础呼吸传导率", "呼吸传导率基础值"],
			"key" \ : "Grs cont"
		}
	]
}
 \  \  \  \  \  \  \  \  \  \  \  \  < div \ id \= "navbar" \ class \= "collapse\ navbar-collapse" >  \ n = {
	"translation" \ : ["< div id \= \\" 导航 \\ " class \= \\" 崩溃navbar - collapse \\ " >"],
	"query" \ : "<div id\=\\" navbar \\ " class\=\\" collapse navbar - collapse \\ ">",
	"errorCode" \ : 0
}
产品名称 = {
	"query" \ : "?ú?·????",
	"errorCode" \ : 30
}
list - cont = {
	"translation" \ : ["list-cont"],
	"query" \ : "list-cont",
	"errorCode" \ : 0
}
企业 = {
	"query" \ : "?ó??",
	"errorCode" \ : 30
}
mysql_query = {
	"translation" \ : ["mysql_query"],
	"query" \ : "mysql_query",
	"errorCode" \ : 0
}
简介 = {
	"query" \ : "?ò?é",
	"errorCode" \ : 30
}
company \  = {
	"translation" \ : ["公司"],
	"basic" \ : {
		"us-phonetic" \ : "'k?mp?ni",
		"phonetic" \ : "'k?mp(?)n?",
		"uk-phonetic" \ : "'k?mp(?)n?",
		"explains" \ : ["n. 公司；陪伴，同伴；连队", "n. (Company)人名；(西)孔帕尼；(英)康帕尼", "vt. 陪伴", "", "vi. 交往"]
	},
	"query" \ : "company",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["公司", "连", "陪伴"],
			"key" \ : "COMPANY"
		}, {
			"value" \ : ["上市公司", "公众公司", "股份上市公司"],
			"key" \ : "public company"
		}, {
			"value" \ : ["公司简介", "公司介绍", "介绍公司"],
			"key" \ : "Company Introduction"
		}
	]
}
调查 = {
	"query" \ : "?",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["?", "?"],
			"key" \ : "?"
		}, {
			"value" \ : ["景泰蓝"],
			"key" \ : "cloiso é"
		}, {
			"value" \ : ["不舒服"],
			"key" \ : "incommodit é"
		}
	]
}
div = {
	"translation" \ : ["div"],
	"basic" \ : {
		"us-phonetic" \ : "div",
		"phonetic" \ : "d?v",
		"uk-phonetic" \ : "d?v",
		"explains" \ : ["abbr. 分开（divide）；区分（division）", "n. (Div)人名；(塞)迪夫；(俄)季夫"]
	},
	"query" \ : "div",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["另一种声音", "定数等分", "块等分"],
			"key" \ : "Div"
		}, {
			"value" \ : ["按钮"],
			"key" \ : "DIV IDE"
		}, {
			"value" \ : ["超漂亮的滑动门", "网站前台", "网页换肤"],
			"key" \ : "CSS DIV"
		}
	]
}
添加 = {
	"translation" \ : ["?í- 1"],
	"query" \ : "?í??",
	"errorCode" \ : 0
}
query = {
	"translation" \ : ["查询"],
	"basic" \ : {
		"us-phonetic" \ : "'kw?ri",
		"phonetic" \ : "'kw??r?",
		"uk-phonetic" \ : "'kw??r?",
		"explains" \ : ["n. 疑问，质问；疑问号 ；[计] 查询", "vi. 询问；表示怀疑", "vt. 询问；对\\u2026\\u2026表示疑问"]
	},
	"query" \ : "query",
	"errorCode" \ : 0,
	"web" \ : [{
			"value" \ : ["查询", "疑问", "询问"],
			"key" \ : "Query"
		}, {
			"value" \ : ["空间查询", "空间查询", "地图查询"],
			"key" \ : "Spatial query"
		}, {
			"value" \ : ["闪回查询", "倒叙查询", "回闪查询"],
			"key" \ : "flashback query"
		}
	]
}
list - con = {
	"translation" \ : ["list-con"],
	"query" \ : "list-con",
	"errorCode" \ : 0
}
端子温度监控断路器 = {
	"query" \ : "??×??????à?????·?÷",
	"errorCode" \ : 30
}
可适用于各类民用建筑 = {
	"translation" \ : ["在????????¨???÷?à????"],
	"query" \ : "?????????÷?à?????¨??",
	"errorCode" \ : 0
}
避免因接线处压线不实 = {
	"query" \ : "±????ò??????????????",
	"errorCode" \ : 30
}
`

notepad++ jstool 格式化了下

**Comment by ice1000** [comment]
目测已经解决了……我URLEncode了中文。

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/52924271-0c3c4500-32fa-11e9-83b2-7eaa8bf8252b.png)
