### ISSUE TITLE
希望queryWord做urlencode处理

### ISSUE THREAD

**Issue by zxcHolmes** [ice1000/A8Translate#4]
https://github.com/ice1000/A8Translate/blob/6c96e10b4bcdebe82e7503b4289099a833912e25/src/org/a8sport/translate/net/HttpUtils.kt#L36

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/52924261-034b7380-32fa-11e9-876c-03842e32f77b.png)
